### ISSUE TITLE
出现227错误，编译失败，有哪位大神有空时帮忙给分析解决一下

### ISSUE THREAD

**Issue by ws245909346** [ppayjjk/ipq6000#5]
Build firmware过程中，出现：
make[1]: *** [tools/Makefile:164: /home/           /openwrt/staging_dir/host/stamp/.tools_compile_yyynyynnyyynyyyynyynnyyyynyyyyyyyyyyyyynynynnyyynynyyy] Error 2
make: *** [/home/        /openwrt/include/toplevel.mk:227:  word]  Error2
Error: Process conpleted with exit code 2.
使用默认pro.config和自定义的pro.config均编译失败，哪位大神能帮忙给分析一下这哪里出现了问题？帮忙给解答一下，已经熬了好几个晚上了。
上半年用sdf的cloud和ipq6000本地编译均没出现过问题，现在不行了，所以试试ppayjjk大神的项目试试，也是不行。

**Comment by ws245909346** [comment]
14个fork中，只有那个360v6编译成功了，其他人都编译出现错误

**Comment by ppayjjk** [comment]
> 14个fork中，只有那个360v6编译成功了，其他人都编译出现错误

我没玩了 所以很久没维护这个了 源项目作者还在搞 你直接去他那里吧

**Comment by ppayjjk** [comment]
> 14个fork中，只有那个360v6编译成功了，其他人都编译出现错误

https://github.com/sdf8057/cloudbuild  sdf的云编译项目
